name: CI for Cloud Resume Challenge site
on:
  push:
    branches:
      - main #here we choose to deploy only when a push is detected on the main branch

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Use your bucket region here

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2 #straight from github docs
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: "/*"
          aws-region: ap-northeast-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
